import { launch, BASE, W, sample } from './lib.mjs';
const b = await launch();
const pg = await (await b.newContext({ viewport: { width: 390, height: 844 }, acceptDownloads: true })).newPage();
const errs = [];
pg.on('console', m => { if (m.type() === 'error') errs.push(m.text().slice(0, 300)); });
pg.on('pageerror', e => errs.push('PAGEERR: ' + String(e).slice(0, 300)));
await sample(pg);
await pg.goto(BASE + '/receipt/p005', W);
await pg.waitForTimeout(5000);
const saveBtn = pg.getByRole('button', { name: 'Save image' });
console.log('save visible?', await saveBtn.isVisible().catch(() => false));
console.log('save disabled?', await saveBtn.isDisabled().catch(() => 'n/a'));
console.log('share text:', await pg.locator('button', { hasText: /Share receipt|Getting image ready/ }).first().innerText().catch(() => 'n/a'));
const dl = pg.waitForEvent('download', { timeout: 8000 }).catch(() => null);
await saveBtn.click().catch(e => console.log('click err', String(e).slice(0, 120)));
const d = await dl;
if (d) { await d.saveAs('/tmp/receipt-test.png'); console.log('saved /tmp/receipt-test.png'); } else console.log('download: NONE');
await pg.waitForTimeout(500);
console.log('status msg:', await pg.locator('[role=status]').first().innerText().catch(() => 'n/a'));
console.log('console errors:', JSON.stringify(errs.slice(0, 5), null, 1));
await b.close();
