import { launch, tally } from './lib.mjs';
const B='http://127.0.0.1:4180', t=tally('shared leagues + consent');
const b=await launch(); const c1=await b.newContext({viewport:{width:390,height:844},permissions:['clipboard-read','clipboard-write']}), c2=await b.newContext({viewport:{width:390,height:844}});
const a=await c1.newPage(), mate=await c2.newPage();
const err=[]; for(const p of [a,mate]) p.on('pageerror',e=>err.push(e.message));
await a.goto(B+'/');
t.check('consent banner before tracking',await a.getByRole('region',{name:'Analytics choice'}).isVisible());
await a.getByRole('button',{name:'No thanks'}).click(); t.check('reject choice saved',await a.evaluate(()=>localStorage.getItem('rally-analytics-consent'))==='no');
await a.getByRole('button',{name:'Try a sample season'}).click(); await a.goto(B+'/leagues');
await a.getByLabel('League name').fill('Mates from phones'); await a.getByRole('button',{name:'Create league'}).click(); await a.waitForURL(/\/leagues\/shared-/,{timeout:5000});
const code=a.url().split('shared-')[1]; t.check('creator gets shared code', /^[A-Z2-9]{6}$/.test(code),code);
await a.locator('table tbody tr').first().waitFor({timeout:5000}); t.check('creator appears in table',/You/.test(await a.locator('table').innerText()));
await mate.goto(B+'/join/'+code); await mate.getByRole('button',{name:'No thanks'}).click(); await mate.getByLabel('Scout name').fill('Mate'); await mate.getByRole('button',{name:'Join league'}).click(); await mate.waitForURL(/\/leagues\/shared-/,{timeout:5000});
t.check('second browser joins same code',mate.url().endsWith(code));
await a.reload(); await a.locator('table tbody tr').nth(1).waitFor({timeout:5000});
t.check('creator sees second device in standings',await a.locator('table tbody tr').count()===2);
const clone=await b.newContext({viewport:{width:390,height:844}}); const stranger=await clone.newPage(); await stranger.goto(B+'/');
const noMember=await stranger.evaluate(async(c)=> {const id=Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join(''); const r=await fetch('/api/leagues/'+c+'/standings',{headers:{'X-Rally-Device':id}}); return r.status},code);
t.check('nonmember cannot read standings',noMember===403,String(noMember));
const missing=await stranger.evaluate(async()=>{const id='a'.repeat(64);return (await fetch('/api/leagues/ZZZZZZ',{headers:{'X-Rally-Device':id}})).status});t.check('missing league yields 404',missing===404);
const cross=await stranger.evaluate(async()=>{const r=await fetch('/api/leagues',{method:'POST',headers:{'X-Rally-Device':'a'.repeat(64),'Content-Type':'application/json','Origin':'https://evil.example'},body:'{}'});return r.status});t.check('invalid create rejected',cross===400 || cross===403);
t.check('no page errors',err.length===0,err.join(' | '));
process.exitCode=t.done();await b.close();
